include::./includes/attributes.adoc[]

Integrate Min.io sdk compatible with all S3 Api complient vendors. Available for jdk and native runtime.

== Project configuration

Once you have your Quarkus project configured you can add the `minio` extension
to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="minio"
----

This will add the following to your `pom.xml`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.minio</groupId>
    <artifactId>quarkus-minio</artifactId>
    <version>{quarkus-minio-version}</version>
</dependency>
----

== Usage

An `io.minio.MinioClient` is made available to your application as a CDI bean if configuration is found.

[source,java]
----
package com.acme.minio;

import io.minio.MinioClient;

import javax.enterprise.context.ApplicationScoped;

import javax.inject.Inject;

@ApplicationScoped
public class SampleService {

    @Inject
    MinioClient minioClient;

    @ConfigProperty(name = "minio.bucket-name")
    String bucketName;

    public String getObject(String name) {
        try (InputStream is = minio.getObject(
                GetObjectArgs.builder()
                        .bucket(bucketName)
                        .object(objectName)
                        .build());
        ) {
           // Do whatever you want...
        } catch (MinioException e) {
            throw new IllegalStateException(e);
        }
    }

}
----

== Configuration Reference

[.configuration-reference, cols="80,.^10,.^10"]
|===

h|Configuration property
h|Type
h|Default

a|icon:lock[title=Fixed at build time] `quarkus.minio.enabled`
--
Should the extension provide a `MinioClient`. If set to `false`, you will have to create the clients yourself, but will still benefit the native compatibility work.
--
|boolean
|`true`

a|`quarkus.minio.url`
--
The minio server URL.
[NOTE]
====
Value must start with `http://` or `https://`
====
--
|string
|

a|`quarkus.minio.access-key`
--
The minio server access key
--
|string
|

a|`quarkus.minio.secret-key`
--
The minio server secret key
--
|string
|

a|`quarkus.minio.region`
--
An optional bucket region
--
|string
|

a|`quarkus.minio.allow-empty`
--
If allow-empty is set to `true` and all other configuration options are empty, `null` is produced instead of the minio client.
--
|string
|

a|`quarkus.minio.produceMetrics`
--
If `true` and the `io.quarkus.quarkus-micrometer` is present in the class path, then the minio client will produce metrics.
--
|boolean
a|`true`
|===

== Multiple Minio clients

=== Configuring Multiple MinioClients

Defining multiple minio clients works exactly the same way as defining a single minio client, with one important change:
you define a name.

In the following example, you have 3 different minio clients:

* The default one,
* A minio client named `other`,
* A minio client named `public`,

each with its own configuration.

[source,properties]
----
quarkus.minio.db-kind=h2
quarkus.minio.username=username-default
quarkus.minio.jdbc.url=jdbc:h2:mem:default
quarkus.minio.jdbc.max-size=13

quarkus.minio.users.db-kind=h2
quarkus.minio.users.username=username1
quarkus.minio.users.jdbc.url=jdbc:h2:mem:users
quarkus.minio.users.jdbc.max-size=11

quarkus.minio.inventory.db-kind=h2
quarkus.minio.inventory.username=username2
quarkus.minio.inventory.jdbc.url=jdbc:h2:mem:inventory
quarkus.minio.inventory.jdbc.max-size=12
----

Notice there is an extra bit in the key.
The syntax is as follows: `quarkus.minio.[optional name.][datasource property]`.

[NOTE]
===
Named databases need to specify at least one build time property so that Quarkus knows they exist.
Generally this will be the `enabled` property.

Also note that `quarkus.minio.produceMetrics` is configured for all minio clients.
====


=== Named MinioClient injection

When using multiple minio clients, each `MinioClient` also has the `io.quarkiverse.minio.client.MinioQualifier` qualifier with the name of the minio client as the value.
Using the above properties to configure three different minio clients, you can also inject each one as follows:

[source,java,indent=0]
----
@Inject
MinioClient defaultMinioClient;

@Inject
@MinioQualifier("public")
MinioClient publicMinioClient;

@Inject
@MinioQualifier("other")
MinioClient otherMinioClient;
----

[[dev-services]]
== Dev Services

Quarkus supports a feature called Dev Services that allows you to create various containers without any config.
What that means in practice is that if you have Docker running and have not configured `quarkus.minio.url`,
Quarkus will automatically start a Minio container when running tests or in dev mode, and automatically
configure the connection.

When running the production version of the application, the Minio connection needs to be configured as normal.

[NOTE]
====
If using multiple minio client, all will target the same container. At the moment it's also not possible to configure devservices individually for each minio client.
====

=== Shared server

Most of the time you need to share the server between applications.
Dev Services for Minio implements a _service discovery_ mechanism for your multiple Quarkus applications running in _dev_ mode to share a single server.

NOTE: Dev Services for Minio starts the container with the `quarkus-dev-service-minio` label which is used to identify the container.

If you need multiple (shared) servers, you can configure the `quarkus.minio.devservices.service-name` attribute and indicate the server name.
It looks for a container with the same value, or starts a new one if none can be found.
The default service name is `minio`.

Sharing is enabled by default in dev mode, but disabled in test mode.
You can disable the sharing with `quarkus.minio.devservices.shared=false`.

=== Configuration

icon:lock[title=Fixed at build time] Configuration property fixed at build time - All other configuration properties are overridable at runtime
[.configuration-reference, cols="80,.^10,.^10"]
|===

h|Configuration property
h|Type
h|Default

a|icon:lock[title=Fixed at build time] `quarkus.minio.devservices.enabled`
--
If DevServices has been explicitly enabled or disabled. DevServices is generally enabled by default, unless there is an existing configuration present. When DevServices is enabled Quarkus will attempt to automatically configure and start a Minio container when running in Dev or Test mode.
--
|boolean
|true

a|icon:lock[title=Fixed at build time] `quarkus.minio.devservices.image-name`
--
The container image name to use, for container based DevServices providers.
--
|String
|`minio/minio:RELEASE.2020-11-10T21-02-24Z`

a|icon:lock[title=Fixed at build time] `quarkus.minio.devservices.shared`
--
Indicates if the Minio server managed by Quarkus Dev Services is shared. When shared, Quarkus looks for running containers using label-based service discovery. If a matching container is found, it is used, and so a second one is not started. Otherwise, Dev Services for Minio starts a new container.
The discovery uses the `quarkus-dev-service-minio` label. The value is configured using the `service-name` property.
Container sharing is only used in dev mode.
--
|boolean
|`true`

a|icon:lock[title=Fixed at build time] `quarkus.minio.devservices.service-name`
--
The value of the `quarkus-dev-service-minio` label attached to the started container. This property is used when `shared` is set to `true`. In this case, before starting a container, Dev Services for Minio looks for a container with the `quarkus-dev-service-minio` label set to the configured value. If found, it will use this container instead of starting a new one. Otherwise, it starts a new container with the `quarkus-dev-service-minio` label set to the specified value.
This property is used when you need multiple shared Minio servers.
--
|String
|`minio`

a|`quarkus.minio.devservices.access-key`
--
Minio root username access key.
--
|String
|`minioaccess`

a|`quarkus.minio.devservices.secret-key`
--
Minio root username secret key.
--
|String
|`miniosecret`

|===
