= Quarkus Minio
include::./includes/attributes.adoc[]

Integrate Min.io sdk compatible with all S3 Api complient vendors. Available for jdk and native runtime.

=== Configuration

Once you have your Quarkus project configured you can add the `minio` extension
to your project by running the following command in your project base directory:

[source,bash]
----
./mvnw quarkus:add-extension -Dextensions="minio"
----

This will add the following to your `pom.xml`:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.minio</groupId>
    <artifactId>quarkus-minio</artifactId>
    <version>{quarkus-minio-version}</version>
</dependency>
----

== Usage

An `io.minio.MinioClient` is made available to your application as a CDI bean if configuration is found.

[source,java,subs=attributes+]
----
package com.acme.minio;

import io.minio.MinioClient;

import javax.enterprise.context.ApplicationScoped;

import javax.inject.Inject;

@ApplicationScoped
public class SampleService {

    @Inject
    MinioClient minioClient;

    @ConfigProperty(name = "minio.bucket-name")
    String bucketName;

    public String getObject(String name) {
        try (InputStream is = minio.getObject(
                GetObjectArgs.builder()
                        .bucket(bucketName)
                        .object(objectName)
                        .build());
        ) {
           // Do whatever you want...
        } catch (MinioException e) {
            throw new IllegalStateException(e);
        }
    }

}
----

=== Configuration Reference

Configuration is done through standard application.properties mechanism.
Configuration is optional, but if present url has to be a valid http url.
If allow-empty is set to `true` and all other configuration options are empty, `null` is produced instead of the minio client.

[source,properties]
----
quarkus.minio.url=https://minio.acme
quarkus.minio.access-key=DUMMY-ACCESS-KEY
quarkus.minio.secret-key=DUMMY-SECRET-KEY
quarkus.minio.region=beyond
quarkus.minio.allow-empty=true/false (Boolean type, default value is false)
----
